steps:
# Step 1: Install necessary dependencies (if required)
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Step 2: Build your static site (if needed)
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

# Step 3: Deploy to App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  timeout: '1600s' # Adjust timeout if needed
